import type { ThemeConfig } from "./types";

export const themes: Record<string, ThemeConfig> = {
  "kc-auto": {
    colors: {
      primary: "#DC2626",
      primaryDark: "#B91C1C",
      primaryLight: "#FCA5A5",
      secondary: "#1E293B",
      background: "#FFFFFF",
      surface: "#F8FAFC",
      surfaceAlt: "#F1F5F9",
      headerBg: "#0F172A",
      footerBg: "#0F172A",
      text: "#1E293B",
      textLight: "#64748B",
      textOnPrimary: "#FFFFFF",
    },
    fonts: { heading: "Bebas Neue", body: "Roboto" },
    borderRadius: "sharp",
    style: "industrial",
  },
  "supreme-blends": {
    colors: {
      primary: "#D4AF37",
      primaryDark: "#B8960F",
      primaryLight: "#F5E6A3",
      secondary: "#1A1A1A",
      background: "#0A0A0A",
      surface: "#1A1A1A",
      surfaceAlt: "#262626",
      headerBg: "#000000",
      footerBg: "#000000",
      text: "#F5F5F5",
      textLight: "#A3A3A3",
      textOnPrimary: "#000000",
    },
    fonts: { heading: "Playfair Display", body: "Lato" },
    borderRadius: "rounded",
    style: "bold",
  },
  "penas-bakery": {
    colors: {
      primary: "#DB2777",
      primaryDark: "#BE185D",
      primaryLight: "#F9A8D4",
      secondary: "#92400E",
      background: "#FFFBEB",
      surface: "#FEF3C7",
      surfaceAlt: "#FDE68A",
      headerBg: "#92400E",
      footerBg: "#78350F",
      text: "#451A03",
      textLight: "#92400E",
      textOnPrimary: "#FFFFFF",
    },
    fonts: { heading: "Playfair Display", body: "Lato" },
    borderRadius: "pill",
    style: "warm",
  },
  "1701-auto-care": {
    colors: {
      primary: "#2563EB",
      primaryDark: "#1D4ED8",
      primaryLight: "#93C5FD",
      secondary: "#F59E0B",
      background: "#FFFFFF",
      surface: "#F0F9FF",
      surfaceAlt: "#E0F2FE",
      headerBg: "#1E3A5F",
      footerBg: "#1E3A5F",
      text: "#1E293B",
      textLight: "#64748B",
      textOnPrimary: "#FFFFFF",
    },
    fonts: { heading: "Montserrat", body: "Open Sans" },
    borderRadius: "rounded",
    style: "modern",
  },
  "fruitvale-collision": {
    colors: {
      primary: "#059669",
      primaryDark: "#047857",
      primaryLight: "#6EE7B7",
      secondary: "#D97706",
      background: "#FFFFFF",
      surface: "#F0FDF4",
      surfaceAlt: "#DCFCE7",
      headerBg: "#1B4332",
      footerBg: "#1B4332",
      text: "#1E293B",
      textLight: "#64748B",
      textOnPrimary: "#FFFFFF",
    },
    fonts: { heading: "Nunito", body: "Source Sans 3" },
    borderRadius: "rounded",
    style: "warm",
  },
  "glenview-automotive": {
    colors: {
      primary: "#0F766E",
      primaryDark: "#115E59",
      primaryLight: "#5EEAD4",
      secondary: "#F59E0B",
      background: "#FFFFFF",
      surface: "#F0FDFA",
      surfaceAlt: "#CCFBF1",
      headerBg: "#134E4A",
      footerBg: "#134E4A",
      text: "#1E293B",
      textLight: "#64748B",
      textOnPrimary: "#FFFFFF",
    },
    fonts: { heading: "Inter", body: "DM Sans" },
    borderRadius: "rounded",
    style: "modern",
  },
  "best-auto-care": {
    colors: {
      primary: "#EA580C",
      primaryDark: "#C2410C",
      primaryLight: "#FDBA74",
      secondary: "#1F2937",
      background: "#FFFFFF",
      surface: "#FFF7ED",
      surfaceAlt: "#FFEDD5",
      headerBg: "#1F2937",
      footerBg: "#1F2937",
      text: "#1E293B",
      textLight: "#64748B",
      textOnPrimary: "#FFFFFF",
    },
    fonts: { heading: "Montserrat", body: "Open Sans" },
    borderRadius: "sharp",
    style: "bold",
  },
  "community-auto": {
    colors: {
      primary: "#0369A1",
      primaryDark: "#075985",
      primaryLight: "#7DD3FC",
      secondary: "#16A34A",
      background: "#FFFFFF",
      surface: "#F0F9FF",
      surfaceAlt: "#E0F2FE",
      headerBg: "#0C4A6E",
      footerBg: "#0C4A6E",
      text: "#1E293B",
      textLight: "#64748B",
      textOnPrimary: "#FFFFFF",
    },
    fonts: { heading: "Nunito", body: "Source Sans 3" },
    borderRadius: "pill",
    style: "warm",
  },
  "aguachiles-el-tamarindo": {
    colors: {
      primary: "#65A30D",
      primaryDark: "#4D7C0F",
      primaryLight: "#BEF264",
      secondary: "#DC2626",
      background: "#FFFFFF",
      surface: "#F7FEE7",
      surfaceAlt: "#ECFCCB",
      headerBg: "#1A2E05",
      footerBg: "#1A2E05",
      text: "#1E293B",
      textLight: "#64748B",
      textOnPrimary: "#FFFFFF",
    },
    fonts: { heading: "Montserrat", body: "Open Sans" },
    borderRadius: "rounded",
    style: "bold",
  },
  "taqueria-el-chacho": {
    colors: {
      primary: "#B91C1C",
      primaryDark: "#991B1B",
      primaryLight: "#FCA5A5",
      secondary: "#F59E0B",
      background: "#FFFBEB",
      surface: "#FEF3C7",
      surfaceAlt: "#FDE68A",
      headerBg: "#450A0A",
      footerBg: "#450A0A",
      text: "#1C1917",
      textLight: "#78716C",
      textOnPrimary: "#FFFFFF",
    },
    fonts: { heading: "Bebas Neue", body: "Roboto" },
    borderRadius: "sharp",
    style: "bold",
  },
  "la-parrilla-loca": {
    colors: {
      primary: "#92400E",
      primaryDark: "#78350F",
      primaryLight: "#FCD34D",
      secondary: "#EF4444",
      background: "#FFFBEB",
      surface: "#FEF3C7",
      surfaceAlt: "#FDE68A",
      headerBg: "#451A03",
      footerBg: "#451A03",
      text: "#1C1917",
      textLight: "#78716C",
      textOnPrimary: "#FFFFFF",
    },
    fonts: { heading: "Nunito", body: "Source Sans 3" },
    borderRadius: "rounded",
    style: "warm",
  },
  pipirin: {
    colors: {
      primary: "#0D9488",
      primaryDark: "#0F766E",
      primaryLight: "#5EEAD4",
      secondary: "#FCD34D",
      background: "#FFFFFF",
      surface: "#F0FDFA",
      surfaceAlt: "#CCFBF1",
      headerBg: "#134E4A",
      footerBg: "#134E4A",
      text: "#1E293B",
      textLight: "#64748B",
      textOnPrimary: "#FFFFFF",
    },
    fonts: { heading: "Inter", body: "DM Sans" },
    borderRadius: "rounded",
    style: "modern",
  },
  "panaderia-la-favorita": {
    colors: {
      primary: "#D97706",
      primaryDark: "#B45309",
      primaryLight: "#FDE68A",
      secondary: "#7C2D12",
      background: "#FFFBEB",
      surface: "#FEF3C7",
      surfaceAlt: "#FDE68A",
      headerBg: "#7C2D12",
      footerBg: "#7C2D12",
      text: "#451A03",
      textLight: "#92400E",
      textOnPrimary: "#FFFFFF",
    },
    fonts: { heading: "Playfair Display", body: "Lato" },
    borderRadius: "pill",
    style: "classic",
  },
  "panaderia-sevilla": {
    colors: {
      primary: "#9333EA",
      primaryDark: "#7E22CE",
      primaryLight: "#D8B4FE",
      secondary: "#F59E0B",
      background: "#FEFCE8",
      surface: "#FAF5FF",
      surfaceAlt: "#F3E8FF",
      headerBg: "#3B0764",
      footerBg: "#3B0764",
      text: "#1E293B",
      textLight: "#64748B",
      textOnPrimary: "#FFFFFF",
    },
    fonts: { heading: "Playfair Display", body: "Lato" },
    borderRadius: "rounded",
    style: "classic",
  },
  "green-eagle-plumbing": {
    colors: {
      primary: "#15803D",
      primaryDark: "#166534",
      primaryLight: "#86EFAC",
      secondary: "#1E40AF",
      background: "#FFFFFF",
      surface: "#F0FDF4",
      surfaceAlt: "#DCFCE7",
      headerBg: "#14532D",
      footerBg: "#14532D",
      text: "#1E293B",
      textLight: "#64748B",
      textOnPrimary: "#FFFFFF",
    },
    fonts: { heading: "Montserrat", body: "Open Sans" },
    borderRadius: "sharp",
    style: "industrial",
  },
};
